version: '3'

services:
  zentao-fastapi:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile_fastapi
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    volumes:
      - .:/app/
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000} --workers ${WORKERS:-1}
  
  
  zentao-fastapi-redis:
    image: redis
    expose:
      - ${REDIS_PORT:-6379}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes    
    restart: unless-stopped


  streamlit:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile_streamlit
    expose:
      - 8501
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app/