FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*


RUN pip install --upgrade pip
COPY .env .
COPY ./streamlit_app/requirements.txt .
RUN pip install -r requirements.txt

COPY ./streamlit_app .

EXPOSE 8501


ENTRYPOINT ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]